namespace Personas.Domain
{
    public enum Comunidad
    {
        Andalucia = 1,
        Aragon = 2,
        Asturias = 3,
        Asturies = 3,
        Baleares = 4,
        Islasbaleares = 4,
        Canarias = 5,
        Islascanarias = 5,
        Cantabria = 6,
        Santander = 6,
        Castillaleon = 7,
        Castillayleon = 7,
        Castillalavieja = 7,
        Castilla = 7,
        Castillalamancha = 8,
        Lamancha = 8,
        Catalunya = 9,
        Cataluna = 9,
        Comunidadvalenciana = 10,
        Comunitatvalenciana = 10,
        Valencia = 10,
        Extremadura = 11,
        Galicia = 12,
        Madrid = 13,
        Comunidadmadrid = 13,
        Comunidaddemadrid = 13,
        Murcia = 14,
        Regiondemurcia = 14,
        Regionmurcia = 14,
        Navarra = 15,
        Paisvasco = 16,
        Euskadi = 16,
        Vascongadas = 16,
        Larioja = 17,
        Rioja = 17,
        Ceuta = 18,
        Melilla = 19,
    }
}
